import { db } from "./db";

async function seed() {
  console.log("🌱 Seeding Veridian Corp data...");

  // -----------------------------
  // KNOWLEDGE BASE
  // -----------------------------
  await db.orm.knowledge_base.createAll([
    {
      code: "KB-01",
      title: "Password Reset",
      category: "Account Access",
      content:
        "Employees can reset their own password via the self-service portal at any time. If locked out after 5 failed attempts, contact IT to unlock the account manually. No approval required.",
      source: "Assignment 2 Data Pack",
    },
    {
      code: "KB-02",
      title: "VPN Access",
      category: "VPN",
      content:
        "VPN access is granted automatically to all full-time employees. Contractors require manager approval submitted via the access request form. VPN credentials expire every 90 days and must be renewed by the employee.",
      source: "Assignment 2 Data Pack",
    },
    {
      code: "KB-03",
      title: "Laptop Replacement",
      category: "Hardware",
      content:
        "Laptops are eligible for replacement after 3 years of service, or earlier in case of verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement.",
      source: "Assignment 2 Data Pack",
    },
    {
      code: "KB-04",
      title: "Software Installation",
      category: "Software",
      content:
        "Standard software listed in the approved catalog can be self-installed. Non-catalog software requires IT Security review, which takes 3–5 business days.",
      source: "Assignment 2 Data Pack",
    },
    {
      code: "KB-05",
      title: "Printer Troubleshooting",
      category: "Hardware",
      content:
        "For printer issues, first check the printer queue and restart the print spooler. If the issue persists after restart, log a ticket with the printer's asset tag.",
      source: "Assignment 2 Data Pack",
    },
    {
      code: "KB-06",
      title: "Email Mailbox Quota",
      category: "Email",
      content:
        "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota increases beyond 25GB require manager approval and are capped at 50GB.",
      source: "Assignment 2 Data Pack",
    },
    {
      code: "KB-07",
      title: "Guest Wi-Fi Access",
      category: "Network",
      content:
        "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket required.",
      source: "Assignment 2 Data Pack",
    },
    {
      code: "KB-08",
      title: "Expense Software Access",
      category: "Software",
      content:
        "Access to the expense management tool is granted by Finance, not IT. IT can only assist with login/technical issues once an account already exists.",
      source: "Assignment 2 Data Pack",
    },
    {
      code: "KB-09",
      title: "Security Incident Reporting",
      category: "Security",
      content:
        "Any suspected phishing email, malware, or unauthorized access attempt must be reported to security@veridian-corp.example immediately and should not be forwarded to other employees.",
      source: "Assignment 2 Data Pack",
    },
    {
      code: "KB-10",
      title: "Work-From-Home Equipment",
      category: "Hardware",
      content:
        "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — IT only handles the equipment shipping request once approved.",
      source: "Assignment 2 Data Pack",
    },
    {
      code: "ASSET-POLICY",
      title: "Asset Management Policy",
      category: "Hardware",
      content:
        "All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval.",
      source: "Finance & Assets — last updated Q2 2026",
    },
  ]);

  // -----------------------------
  // EMPLOYEE REQUESTS
  // -----------------------------
  await db.orm.employee_requests.createAll([
    {
      code: "REQ-01",
      employee: "Aditi Sharma",
      requestDate: "Mon 21 Sep",
      request:
        "My laptop won’t turn on at all, it’s completely dead, had it about 3.5 years now.",
      status: "Not started",
      details: "aditi.sharma@veridian-corp.example",
    },
    {
      code: "REQ-02",
      employee: "Vikram Chawla",
      requestDate: "Mon 21 Sep",
      request:
        "Can I get Wi-Fi access for a guest visiting our office tomorrow?",
      status: "Not started",
      details: "vikram.chawla@veridian-corp.example",
    },
    {
      code: "REQ-03",
      employee: "Karan Mehta",
      requestDate: "Mon 21 Sep",
      request: "I’m locked out of my account, tried my password 6 times.",
      status: "In progress — reset queued",
      details: "karan.mehta@veridian-corp.example",
    },
    {
      code: "REQ-04",
      employee: "Ritu Bhatia",
      requestDate: "Tue 22 Sep",
      request:
        "Need approval to install a data-analysis tool that’s not in the software catalog.",
      status: "Waiting on Security review",
      details: "ritu.bhatia@veridian-corp.example",
    },
    {
      code: "REQ-05",
      employee: "Sanjay Oberoi",
      requestDate: "Tue 22 Sep",
      request: "My VPN stopped working this morning, says credentials expired.",
      status: "Not started",
      details: "sanjay.oberoi@veridian-corp.example",
    },
    {
      code: "REQ-06",
      employee: "Meera Iyer",
      requestDate: "Tue 22 Sep",
      request:
        "Printer on the 3rd floor keeps showing “paper jam” even though there’s no jam.",
      status: "Investigating — technician assigned",
      details: "meera.iyer@veridian-corp.example",
    },
    {
      code: "REQ-07",
      employee: "Farhan Ali",
      requestDate: "Wed 23 Sep",
      request:
        "I’ve started working from home 4 days a week, how do I get a monitor?",
      status: "Not started",
      details: "farhan.ali@veridian-corp.example",
    },
    {
      code: "REQ-08",
      employee: "Ananya Reddy",
      requestDate: "Wed 23 Sep",
      request:
        "I think I got a phishing email asking for my login — forwarding it to a few teammates to check.",
      status: "Escalated to Security (auto-flagged)",
      details: "ananya.reddy@veridian-corp.example",
    },
    {
      code: "REQ-09",
      employee: "Rohit Desai",
      requestDate: "Wed 23 Sep",
      request: "My mailbox is full and I can’t send emails.",
      status: "Not started",
      details: "rohit.desai@veridian-corp.example",
    },
    {
      code: "REQ-10",
      employee: "Kavya Pillai",
      requestDate: "Wed 23 Sep",
      request:
        "Can someone give me admin access to the finance reporting server? Need it urgently for month-end.",
      status: "Not started",
      details: "kavya.pillai@veridian-corp.example",
    },
    {
      code: "REQ-11",
      employee: "Nikhil Bansal",
      requestDate: "Thu 24 Sep",
      request:
        "New contractor joining my team next week, they’ll need VPN access.",
      status: "Not started",
      details: "nikhil.bansal@veridian-corp.example",
    },
    {
      code: "REQ-12",
      employee: "Sneha Kulkarni",
      requestDate: "Thu 24 Sep",
      request:
        "I can’t log into the expense tool, keeps saying invalid credentials.",
      status:
        "Waiting on employee response (asked for a screenshot, no reply yet)",
      details: "sneha.kulkarni@veridian-corp.example",
    },
    {
      code: "REQ-13",
      employee: "Aman Gupta",
      requestDate: "Thu 24 Sep",
      request:
        "Laptop screen is flickering on and off, had it 2 years, might just need a fix not a replacement.",
      status: "Not started",
      details: "aman.gupta@veridian-corp.example",
    },
    {
      code: "REQ-14",
      employee: "Tanya Chopra",
      requestDate: "Fri 25 Sep",
      request:
        "Requesting approval to install a browser extension for productivity tracking.",
      status: "Not started",
      details: "tanya.chopra@veridian-corp.example",
    },
    {
      code: "REQ-15",
      employee: "Rahul Menon",
      requestDate: "Fri 25 Sep",
      request: "hey can you help, its not working",
      status: "Not started",
      details: "rahul.menon@veridian-corp.example",
    },
  ]);

  // -----------------------------
  // TICKET QUEUE
  // -----------------------------
  await db.orm.tickets.createAll([
    {
      code: "TK-1042",
      employee: "R. Verma",
      issue: "VPN credential expired",
      status: "Resolved (closed)",
      details: null,
    },
    {
      code: "TK-1043",
      employee: "S. Iyer",
      issue: "Laptop replacement (3.2 yrs old)",
      status: "Approved — pending fulfillment (active)",
      details: null,
    },
    {
      code: "TK-1044",
      employee: "A. Khan",
      issue: "Non-catalog software request",
      status: "Pending Security review (active)",
      details: null,
    },
    {
      code: "TK-1045",
      employee: "P. Joshi",
      issue: "Mailbox quota increase",
      status: "Approved at 35GB (closed)",
      details: null,
    },
    {
      code: "TK-1046",
      employee: "M. Das",
      issue: "Printer paper jam, floor 2",
      status: "Resolved (closed)",
      details: null,
    },
    {
      code: "TK-1047",
      employee: "K. Singh",
      issue: "Home office equipment request",
      status: "Pending Finance (active)",
      details: null,
    },
    {
      code: "TK-1048",
      employee: "T. Rao",
      issue: "Phishing email reported",
      status: "Escalated to Security — under investigation (active)",
      details: null,
    },
    {
      code: "TK-1049",
      employee: "V. Nambiar",
      issue: "Password reset",
      status: "Resolved (closed)",
      details: null,
    },
    {
      code: "TK-1050",
      employee: "J. Fernandes",
      issue: "Admin access request",
      status: "Rejected — no business justification provided (closed)",
      details: null,
    },
    {
      code: "TK-1051",
      employee: "L. Menon",
      issue: "Guest Wi-Fi issued",
      status: "Resolved (closed)",
      details: null,
    },
  ]);

  console.log("✅ Knowledge base seeded");
  console.log("✅ Employee requests seeded");
  console.log("✅ Ticket queue seeded");
  console.log("🎉 Veridian Corp data seeding complete!");
}

seed().catch((error) => {
  console.error("❌ Seeding failed:");
  console.error(error);
  process.exit(1);
});
