// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
  RelationKeys,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'9e3fca252f4e1cf849168ca48cadee64672221bea3a83c8ca38a2917dd0965f5'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly EmployeeRequest: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly code: CodecTypes['mongo/string@1']['output'];
      readonly employee: CodecTypes['mongo/string@1']['output'];
      readonly requestDate: CodecTypes['mongo/string@1']['output'];
      readonly request: CodecTypes['mongo/string@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly details: CodecTypes['mongo/string@1']['output'] | null;
    };
    readonly KnowledgeBase: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly code: CodecTypes['mongo/string@1']['output'];
      readonly title: CodecTypes['mongo/string@1']['output'];
      readonly category: CodecTypes['mongo/string@1']['output'];
      readonly content: CodecTypes['mongo/string@1']['output'];
      readonly source: CodecTypes['mongo/string@1']['output'];
    };
    readonly Ticket: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly code: CodecTypes['mongo/string@1']['output'];
      readonly employee: CodecTypes['mongo/string@1']['output'];
      readonly issue: CodecTypes['mongo/string@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly details: CodecTypes['mongo/string@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly EmployeeRequest: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly code: CodecTypes['mongo/string@1']['input'];
      readonly employee: CodecTypes['mongo/string@1']['input'];
      readonly requestDate: CodecTypes['mongo/string@1']['input'];
      readonly request: CodecTypes['mongo/string@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly details: CodecTypes['mongo/string@1']['input'] | null;
    };
    readonly KnowledgeBase: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly code: CodecTypes['mongo/string@1']['input'];
      readonly title: CodecTypes['mongo/string@1']['input'];
      readonly category: CodecTypes['mongo/string@1']['input'];
      readonly content: CodecTypes['mongo/string@1']['input'];
      readonly source: CodecTypes['mongo/string@1']['input'];
    };
    readonly Ticket: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly code: CodecTypes['mongo/string@1']['input'];
      readonly employee: CodecTypes['mongo/string@1']['input'];
      readonly issue: CodecTypes['mongo/string@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly details: CodecTypes['mongo/string@1']['input'] | null;
    };
  };
};

export namespace Models {
  export type unbound_KnowledgeBase = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    code: CodecTypes['mongo/string@1']['output'];
    title: CodecTypes['mongo/string@1']['output'];
    category: CodecTypes['mongo/string@1']['output'];
    content: CodecTypes['mongo/string@1']['output'];
    source: CodecTypes['mongo/string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_EmployeeRequest = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    code: CodecTypes['mongo/string@1']['output'];
    employee: CodecTypes['mongo/string@1']['output'];
    requestDate: CodecTypes['mongo/string@1']['output'];
    request: CodecTypes['mongo/string@1']['output'];
    status: CodecTypes['mongo/string@1']['output'];
    details: CodecTypes['mongo/string@1']['output'] | null;
    readonly [RelationKeys]?: never;
  };
  export type unbound_Ticket = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    code: CodecTypes['mongo/string@1']['output'];
    employee: CodecTypes['mongo/string@1']['output'];
    issue: CodecTypes['mongo/string@1']['output'];
    status: CodecTypes['mongo/string@1']['output'];
    details: CodecTypes['mongo/string@1']['output'] | null;
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  __unbound__: {
    KnowledgeBase: Models.unbound_KnowledgeBase;
    EmployeeRequest: Models.unbound_EmployeeRequest;
    Ticket: Models.unbound_Ticket;
  };
};

export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly employee_requests: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'code'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly code: { readonly bsonType: 'string' };
                    readonly employee: { readonly bsonType: 'string' };
                    readonly requestDate: { readonly bsonType: 'string' };
                    readonly request: { readonly bsonType: 'string' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly details: { readonly bsonType: readonly ['null', 'string'] };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'code',
                    'employee',
                    'request',
                    'requestDate',
                    'status',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly knowledge_base: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'code'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly code: { readonly bsonType: 'string' };
                    readonly title: { readonly bsonType: 'string' };
                    readonly category: { readonly bsonType: 'string' };
                    readonly content: { readonly bsonType: 'string' };
                    readonly source: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'category',
                    'code',
                    'content',
                    'source',
                    'title',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly tickets: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'code'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly code: { readonly bsonType: 'string' };
                    readonly employee: { readonly bsonType: 'string' };
                    readonly issue: { readonly bsonType: 'string' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly details: { readonly bsonType: readonly ['null', 'string'] };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'code', 'employee', 'issue', 'status'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly knowledge_base: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'KnowledgeBase';
    };
    readonly employee_requests: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'EmployeeRequest';
    };
    readonly tickets: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Ticket' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly EmployeeRequest: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly code: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly employee: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly requestDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly request: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly details: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'employee_requests' };
          };
          readonly KnowledgeBase: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly code: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly source: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'knowledge_base' };
          };
          readonly Ticket: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly code: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly employee: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly issue: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly details: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'tickets' };
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
